spring.application.name=stockengine

spring.datasource.url=jdbc:h2:mem:stockengine-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


spring.kafka.admin.auto-create-topics=true

